#km endpoint
endpoint: https://cf8bsxme.com
#save in db
save: false
download: True
#thread num
pool_size: 16

#define database connect configuration
db:
  host: 127.0.0.1
  port: 3306
  user: root
  pass: root
  database: km



